### PR TITLE
Moving to sc-machine 0.6.0

### PR DESCRIPTION
**Pull request by FallenChromium**
Pretty much the title. Additionally I've added a CMake rule to link glib-2.0 on macOS, so now the demo works on Macintosh, too.

One problem I've noticed while migrating to sc-machine 0.6.0 is that the program doesn't shut down correctly:
```
The end
[13:36:37][Info]: Shutdown module: /Users/<censored>/OSTIStown/hell/ostis-0.6.0/sc-machine/bin/extensions/libsc-ui.dylib
[13:36:37][Info]: Shutdown module: /Users/<censored>/OSTIStown/hell/ostis-0.6.0/sc-machine/bin/extensions/libsc-search.dylib
[13:36:37][Info]: Shutdown module: /Users/<censored>/OSTIStown/hell/ostis-0.6.0/sc-machine/bin/extensions/libsc-agents-common.dylib
[13:36:37][Info]: Shutdown module: /Users/<censored>/OSTIStown/hell/ostis-0.6.0/sc-machine/bin/extensions/libsc-utils.dylib
libc++abi: terminating with uncaught exception of type utils::ExceptionInvalidState: std::exception
```
The next time I try to launch the `wave` app, it initialises about 5 times slower than usual. Rebuilding the KB fixes this problem, and I shall say that it's not the app's problem - it also happens with all the other cpp sc-memory projects I've seen so far.

### CODE REVIEW

**Comment by FallenChromium** [comment]
@MikhailSadovsky, do you have any suggestions about this PR? Feedback would be appreciated :)

**Review by MikhailSadovsky — CHANGES_REQUESTED** [review]
Thanks for contribution! Please update README file accordingly as there is stil 0.5.0 version mentioned

**Comment by FallenChromium** [comment]
I've got an idea: we can include a quick GIF demonstration on installation and running the project, it may help if some instructions are not clear for students. I've compressed them a lot, but they still should be readable. GitHub generated a permalink on this document, so we can just include a link to the GIF, without uploading it to the repo itself

Initial installation:

wave-find-path-installation

Running with VS Code (I believe it is way easier to do than with CLion btw):

wave-find-path-running-vscode

Tell me what you think about it, if everything's alright I'm going to include these gifs in the README.md

**Comment by MikhailSadovsky** [comment]
> I've got an idea: we can include a quick GIF demonstration on installation and running the project, it may help if some instructions are not clear for students. I've compressed them a lot, but they still should be readable. GitHub generated a permalink on this document, so we can just include a link to the GIF, without uploading it to the repo itself
> 
> Initial installation:
> 
> wave-find-path-installation
> 
> Running with VS Code (I believe it is way easier to do than with CLion btw):
> 
> wave-find-path-running-vscode
> 
> Tell me what you think about it, if everything's alright I'm going to include these gifs in the README.md

Great, let's add this

**Review by MikhailSadovsky — APPROVED** [review]

**Pull request merged**
